version: '3.7'

services:
    vegeta-varload:
        build:
            context: .
        entrypoint: /root/vegeta-varload --url http://nginx/ --pacer step-function --file attack.csv
    
    nginx:
        image: nginx
        ports:
        - 8080
