version: '3.7'

services:
    vegeta:
        build:
            context: .
        entrypoint: /root/vegeta_varload http://nginx/
    
    nginx:
        image: nginx
        ports:
        - 8080
        command: [nginx, '-g', 'daemon off;']
